### ISSUE TITLE
Sega 32X emulator running very slow .

### ISSUE THREAD

**Issue by mfwhite** [neilmunday/pes#1]
Hello Neil , I tested the new version of PES and really enjoyed the addition of new emulators in this latest version 1.5, but the speed of the Sega 32X emulator is very slow , practically unplayable . I know we can optimize it for the Raspberry Pi , since other systems can run on almost perfection ( Recalbox ) . I'm not charging anything , even by offering this great system for free for us, but really want the PES to become one of the best platforms for Retro emulation on Raspberry Pi . I take this opportunity to thank you for being listening to users and aparfeiçoando increasingly your system. Thank you and congratulations for the great job so far.

RaspberryPiBR

**Comment by neilmunday** [comment]
Hi,

Thanks for the feedback.

Just to check are you using PES 1.5 on a Raspberry Pi or Raspberry Pi 2?

Also which games have you tried so I can try and repeat the issue?

Thanks,

Neil.

**Comment by mfwhite** [comment]
Hello Neil , I tested now the version for ARMv6 on my Raspberry Pi B + , because before I had only tested the version for Raspberry Pi 2. What I can say is that the version for ARMv6 has a performance slightly better than the version for ARMv7 the games are running fairly well, but with a lot of latency in audio . In the version for ARMv7 the games run very slow and very lantencia in audio as well. The games I tested in both versions are Virtua Fighter, Time, BC Racers , X -Men, Virtua Racing Deluxe , Blackthorne and Spider Man Web of Shadows .

**Comment by neilmunday** [comment]
Thanks for the info. I've been able to repeat what you are seeing with those games. I'll see what I can do.

**Comment by neilmunday** [comment]
I have corrected the build options for PicoDrive and it now runs much better.

PES 1.5.1. will be released this week with the newly compiled PicoDrive libretro core.

Thanks again for reporting the issue.

**Comment by mfwhite** [comment]
I do thank you Neil . You are quite attentive to the users of your system.

**Comment by neilmunday** [comment]
No problem. PES 1.5.1 can now be downloaded. See http://pes.mundayweb.com/html/index.html#download

**Comment by mfwhite** [comment]
Hello Neil, I downloaded yesterday and the new version is excellent. I tested 37 games of 32X and all worked with great speed and most with perfect audio. Just noticed problem in audio two games (Virtua Fighter and Tempo), do not know if these games had some special audio chip (Tempo has a great soundtrack). Congratulations for a great job and once again thank you.

**Comment by neilmunday** [comment]
Hi. Glad to hear the new version is working for you. I also found that the audio with Virtua Fighter was a bit off. This list doesn't mention any audio problems (not tested on Raspberry Pi), but there are some 32x games that have known issues: https://github.com/notaz/picodrive/wiki/Compability-list-picodrive

**Comment by mfwhite** [comment]
Hello Neil, I wonder what extension to the roms if Atari 2600, because I
tried .A26, .bin and .ROM and none worked. Thank you.
Em 04/11/2015 20:18, "Neil Munday" <notifications@github.com> escreveu:

Hi,

Thanks for the feedback.

Just to check are you using PES 1.5 on a Raspberry Pi or Raspberry Pi 2?

Also which games have you tried so I can try and repeat the issue?

Thanks,

Neil.

—
Reply to this email directly or view it on GitHub
<https://github.com/neilmunday/pes/issues/1#issuecomment-153887012>.

**Comment by mfwhite** [comment]
Hello Neil, I wonder what extension to the roms if Atari 2600, because I tried .A26, .bin and .ROM and none worked. Thank you.

**Comment by neilmunday** [comment]
Hi. A good question, I forgot to update the docs to say which extensions PES looks for. At present it looks for ".zip" only.

However, you can change this by editing /home/pi/pes/conf.d/pes/consoles.ini (https://github.com/neilmunday/pes/blob/master/conf.d/pes/consoles.ini) and add to the list of extensions the ones you want.

You can also access this file via Windows File Sharing by typing "\\pes" into Windows Explorer.

Alternatively, I've just updated my repository version of consoles.ini to include ".bin". Therefore, if you run "/home/pi/pes/bin/update.sh" your Raspberry Pi will get the new version.

Let me know how you get on.

I'll also update the PES 1.5. documentation.

**Comment by mfwhite** [comment]
I also wonder if you could add support for the PC Engine CD / Turbografx 16 CD? Thanks for listening.

**Comment by neilmunday** [comment]
According to http://wiki.libretro.com/index.php?title=Beetle/Mednafen_PCE_FAST the emulator does support PC Engine CD / Turbografx 16 CD, but you need to the correct BIOS file: syscard3.pce to use such ROMs.

**Comment by mfwhite** [comment]
Hello Neil, sorry for the delay in responding. I know this emulator supports PC Engine CD / Turbografx 16 CD, but I've tried putting the bios in the bios folder and even on the roms own folder and it can not run the CD roms. Already edited the file to the emulator recognize the extensions .bin .iso and .cue, but nothing worked. You could try to see what might be happening? You have much more experience and skill than me. Thanks again.

**Comment by neilmunday** [comment]
Hi Michelle, no need to apologise. I've done some testing and I can get some PC Engine CD / Turbografx 16 CD games to work if they are in ISO and CUE format (i.e. a CUE file together with a corresponding ISO).

First tell PES to look for ".cue" files - do not include ".iso" in consoles.ini.

Next make sure the file name in the cue file for the ISO is encapsulated with double quotes.

Finally, make sure the BIOS file is in the BIOS directory for PES and all should work.

I've tested the Adams Family this way and it worked great.

It's worth noting this issue: https://github.com/libretro/beetle-pce-fast-libretro/issues/12 it would seem that some ISOs don't work due to audio compatibility issues.
