### ISSUE TITLE
Berryboot images

### ISSUE THREAD

**Issue by symbios24** [neilmunday/pes#19]
Hello great OS
Is it possible to release Berryboot images also?
I tried to convert it but it did not work

Thank you

**Comment by neilmunday** [comment]
Hi,

Glad to hear you like PES.

I've not used BerryBoot. Their documentation for adding a new OS seems rather lacking at the moment: http://www.berryterminal.com/doku.php/berryboot/adding_custom_distributions

PES for the Raspberry Pi uses Arch Linux as the OS. Guides for adding Arch Linux to BerryBoot should work for PES, however, upon the first boot of PES it tries to create a FAT32 /data partition that occupies all remaining free space on the SD card. I'm not sure this stage will work as it stands at present.

When I get some free time, I'll take a look into this further - hopefully the BerryBoot folk might have fixed their site by then!

Cheers,

Neil.

**Comment by symbios24** [comment]
Ok thanks i will wait

**Comment by neilmunday** [comment]
@symbios24 just to let you know that I have got a BerryBoot image of the PES 2.2 BETA from Raspberry Pi 2/3 to work. Would you be interested in trying it out?

**Comment by neilmunday** [comment]
Raspberry Pi 2/3 PES 2.2 BETA BerryBoot image is available for testing from: http://pes.mundayweb.com/pes-2.2-BETA-2017-05-21-rpi2-3-berryboot.img256.gz

md5sum: d95454c0de317ef55ddc6948caf18276

**Comment by symbios24** [comment]
Hello thanks i will try them

**Comment by neilmunday** [comment]
@symbios24 have you had a chance to try out the BerryBoot image above?

**Comment by neilmunday** [comment]
Worked ok here, closing issue.

**Comment by neilmunday** [comment]
BerryBoot images for PES 2.3 can now be found at: https://pes.mundayweb.com/html/BerryBoot.html
