### ISSUE TITLE
Berryboot + PES on PI 3b+ getting faultmessage "Failed to activate swap /swapfile

### ISSUE THREAD

**Issue by p-dae** [neilmunday/pes#48]
Berryboot + PES on PI 3b+ getting faultmessage:
"Failed to activate swap /swapfile"
"dependancy failed for Swap"

Berryboot and PES are installed on SD, so no USB or portable

Any idea how to solve?

**Comment by neilmunday** [comment]
Thanks for reporting the issue. I have been able to repeat it with my Raspberry Pi 3 and the PES 2.9 BerryBoot image.

**Comment by neilmunday** [comment]
Upon further investigation, the error is due to trying to use a swap file inside the BerryBoot overlay.

It can be ignored.

You can remove the use of the swap file to remove the error seen by commenting out (or deleting) the `/swapfile` entry in `/etc/fstab`.

E.g.

```bash
sudo vi nano /etc/fstab
```

**Comment by neilmunday** [comment]
I've updated https://pes.mundayweb.com/html/BerryBoot.html to note the error can be ignored.
